pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/romchykk/task4.git', branch: 'main'
            }
        }
        
        stage('Build') {
            steps {

                bat '"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\MSBuild.exe" vs_mkr_test1\\test_repos.sln /t:Build /p:Configuration=Debug /p:Platform=x64'
            }
        }
        
        stage('Test') {
            steps {

                bat "vs_mkr_test1\\x64\\Debug\\test_repos.exe --gtest_output=xml:test_report.xml"
            }
        }
    }
    
    post {
        always {

            junit(testResults: 'vs_mkr_test1/test_report.xml', skipOldReports: true, healthScaleFactor: 1.0)

            cleanWs()
        }
    }
}
